apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hayrihabip
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: hayrihabip
        tier: backend
        track: stable
    spec:
      containers:
      - name: hayrihabip-container
        image: 35hhcontainers.azurecr.io/api.hayrihabip.com:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
