service: hayrihabip
plugins:
  - serverless-offline
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  lambdaHashingVersion: 20201221
  memorySize: 192
  timeout: 10
package:
  patterns:
    - '!**'
    - 'node_modules/@vendia/**'
    - 'node_modules/aws-serverless-express/**'
    - 'node_modules/binary-case/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/mime-db/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/type-is/**'
    - 'dist/**'
    - 'lambda.js'
custom:
  apigwBinary:
    types:
      - '*/*'
functions:
  api:
    handler: lambda.handler
    events:
      - http: GET /
      - http: GET /{proxy+}
    # handler: lambda.universal
    # events:
    #   - http: ANY {proxy+}
    #   - http: ANY /
